---
# Java — path auto-detected after install
java_home: "/usr/lib/jvm/java-17-openjdk"
jdk_package: "java-17-openjdk-devel"

# WebLogic installer S3 location
wls_s3_bucket: "weblogic379063509598 "
wls_s3_key: "fmw_14.1.2.0.0_wls.jar"

# WebLogic Installer
wls_installer: "fmw_14.1.2.0.0_wls.jar"
wls_installer_path: "/tmp/weblogic"

# Oracle Paths
oracle_base: "/u01/app/oracle"
oracle_home: "/u01/app/oracle/product/14.1.2/wlserver"
oracle_inventory: "/u01/app/oraInventory"

# Domain
wls_domain_name: "base_domain"
wls_domain_home: "/u01/app/oracle/user_projects/domains"
wls_admin_port: 7001

# OS User
oracle_user: "oracle"
oracle_group: "oinstall"
oracle_uid: 1200
oracle_gid: 1200

# Admin credentials (from vault)
wls_admin_user: "weblogic"
wls_admin_password: "{{ vault_wls_admin_password }}"

# Python interpreter
ansible_python_interpreter: /usr/bin/python3

# Directories to create
oracle_dirs:
  - "{{ oracle_base }}"
  - "{{ oracle_home }}"
  - "{{ oracle_inventory }}"
  - "{{ wls_installer_path }}"
  - "{{ wls_domain_home }}"
