---
oracle_user: "oracle"
oracle_group: "oinstall"
oracle_uid: 1200
oracle_gid: 1200
java_home: "/usr/lib/jvm/java-17-openjdk"
oracle_base: "/u01/app/oracle"
oracle_home: "/u01/app/oracle/product/14.1.2/wlserver"
oracle_inventory: "/u01/app/oraInventory"
wls_installer: "fmw_14.1.2.0.0_wls.jar"
wls_installer_path: "/tmp/weblogic"
wls_domain_name: "base_domain"
wls_domain_home: "/u01/app/oracle/user_projects/domains"
wls_admin_port: 7001
wls_admin_user: "weblogic"
oracle_dirs:
  - "/u01/app/oracle"
  - "/u01/app/oracle/product/14.1.2/wlserver"
  - "/u01/app/oraInventory"
  - "/tmp/weblogic"
  - "/u01/app/oracle/user_projects/domains"

# These are set directly in AAP Job Template Extra Variables
# wls_admin_password: set in AAP
# wls_download_url: set in AAP