# ec2_inventory.yml (AWS Dynamic Inventory)
plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
filters:
  instance-state-name: running
  tag:Role: weblogic
keyed_groups:
  - prefix: env
    key: tags.Environment
hostnames:
  - private-ip-address
compose:
  ansible_host: private_ip_address