[weblogic_servers]
wls-node1 ansible_host=192.168.163.131
wls-node2 ansible_host=192.168.163.133

[all:vars]
ansible_user=amd
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
